FROM node:20-slim
WORKDIR /memoire
ENV NODE_ENV=production

COPY --chown=node:node node_modules ./node_modules
COPY --chown=node:node dist ./dist
COPY --chown=node:node package.json .

USER node

CMD ["node", "--enable-source-maps", "dist/index.js"]
LABEL org.opencontainers.image.source=https://github.com/A-star-logic/memoire