# This is an example of how to configure Memoire with docker-compose.
services:
  memoire:
    image: ghcr.io/a-star-logic/memoire:latest
    container_name: Memoire
    ports:
      - 3003:3003
    environment:
      - API_KEY=abc123 # an API key is required, make it secure (ex: use `openssl rand -hex 32`)
      - SHOW_DOC=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - .memoire:/memoire/.memoire
      # or - your/local/path:/memoire/.memoire
