run-name: Deploy api

on:
  pull_request:
  push:
    branches: [main]

  # Allow manual trigger
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  transpile:
    name: Transpile
    runs-on: ubuntu-latest
    container: node:20-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Transpile
        run: yarn build
        shell: bash

      - name: Save artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          compression-level: 0
          retention-days: 1
          name: dist
          path: |
            dist/*
      # need an additional step for saving the maps to Sentry

  # Having multiple jobs allow the equivalent of multi-stage builds in docker; but we can leverage more easily github cache from the action workflow
  build:
    needs: transpile
    name: Build
    runs-on: ubuntu-latest
    container: node:20-slim
    environment: production
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Use cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Production packages
        run: yarn workspaces focus -A --production
        shell: bash

      - name: Clean TS, build, test files...
        run: |
          find . -name '*.ts' -delete
          find . -name '**/test/*' -delete
          find . -name '**/tests/*' -delete
          find . -name '*.tsbuildinfo' -delete
          find . -name '*.md' -delete

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/memoire:latest, ghcr.io/memoire:${{ github.sha }}
          file: ./docker/Dockerfile.memoire
          context: ./
