run-name: Quality assurance

on:
  pull_request:
    paths:
      - 'src/**'
      - 'docker/Dockerfile.memoire'
      - 'package.json'

concurrency:
  # cancel any running action on new push
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  transpile:
    name: Transpile
    runs-on: ubuntu-latest
    container: node:20-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Transpile
        run: yarn build
        shell: bash

  license-check:
    name: License check
    runs-on: ubuntu-latest
    container: node:20-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: License check
        run: yarn lint:licenses

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: node:20-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: ESLint
        run: yarn lint:eslint --quiet

      - name: Prettier
        run: yarn lint:prettier

      - name: TSC
        run: yarn lint:tsc

  Test:
    name: Test
    runs-on: ubuntu-latest
    container: node:20-slim
    environment: cicd
    permissions:
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Test
        run: yarn test:ci
        env:
          NODE_ENV: test
          GITHUB_ACTIONS: true # enable github actions reporter for vitest
          API_KEY: secret
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: us-east-1
          POSTHOG_KEY: secret
          SENTRY_DSN: secret

      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2
